## [특강] Numpy, Pandas, Matplotlib

### 2. Pandas 기본 구조: Series와 DataFrame

- numpy = dataframe 행과 열로 구성
- 각각의 행 column = "series", 1차원 구조체
- 시리즈 여러개 == 데이터프레임

#### 2.1 Series와 DataFrame
Series

- series와 인덱스 함께 출력

In [ ]:
import pandas as pd
scores = pd.Series([90, 85, 88])
print(scores)
print(type(scores))

DataFrame

- 2차원(행, 열) 구조체
- 행 인덱스 + 열 이름 column

In [ ]:
data = {
    "이름": ["김철수", "이영희", "박민수"],  
    "부서": ["개발", "기획", "개발"],
    "급여": [4500, 5200, "4800"]
}

df = pd.DataFrame(data)
print(df) # 행 인덱스 0부터 시작 + column은 이름, 부서, 급여

#### 2.2 데이터 탐색 속성(shape, dtypes)과 진단(info, describe)

- 탐색적 데이터 분석(EDA)
- `df.info()`
    - 누락치 확인(Non-Null Count)
    - dtype: 통계가 가능한 자료형인지 체크(잘못된 데이터가 있는지 여부 확인 -> 치환 -> 자료형 변환)

- `df.describe()`
    - 평균, 중앙값, 최대, 최소값을 통해서 이상치(극단치) 확인

In [ ]:
print("df.info()")
df.info() # info()를 통해 dtype 체크, object 존재시 통계 불가(숫자가 str으로 되어 있음)

In [ ]:
data = {
    "이름": ["김철수", "이영희", "박민수"],  
    "부서": ["개발", "기획", "개발"],
    "급여": [4500, 5200, 48000]
}

df = pd.DataFrame(data)

df.describe() # max값=이상치

#### 2.3 데이터 변경 및 인덱스 제어(set_index, reset_index)

In [ ]:
# df['급여'], type(df['급여'])

# 보너스 column 추가
df['보너스'] = df['급여'] * 0.1
df

In [ ]:
# 인덱스를 변경하는 경우
df_indexed = df.set_index('이름')
df_indexed

In [ ]:
# 변경한 인덱스를 다시 숫자형 인덱스로 초기화
df_restored = df_indexed.reset_index('이름')
df_restored # new dataframe
print(df_restored)
print(df is df_restored) # False

#### 2.4 Pandas Series & DataFrame 브로드캐스팅 연산

- axis: 0: -> 행 index 기준
- axis: 1: -> 열 index 기준

In [ ]:
df = pd.DataFrame({
    '중간고사': [80, 95, 70],
    '기말고사': [85, 90, 75] #인덱스 총 3개 (0, 1, 2)
}, index=['김철수', '이영희', '박민수']) # index=로 인덱스 설정 DataFrame({data dictionary}, index=[value 개수])

# df = df.set_index("김철수", "이영희", "박민수") DOESNT WORK

df

     중간고사  기말고사
김철수    80    85
이영희    95    90
박민수    70    75

In [47]:
# 각 시험별 (column에 대한) 평균 series 계산 -> axis=0. 행 기준(인덱스 기준)
score_means = df.mean(axis=0)
score_means

중간고사    81.666667
기말고사    83.333333
dtype: float64

In [48]:
means_per_student = df.mean(axis=1)
means_per_student

김철수    82.5
이영희    92.5
박민수    72.5
dtype: float64

In [ ]:
score_gap = df.sub(score_means, axis=1) # 학생 실제 점수 - 시험 평균
score_gap

          중간고사      기말고사
김철수  -1.666667  1.666667
이영희  13.333333  6.666667
박민수 -11.666667 -8.333333

### 3. Pandas 정밀 조회 및 결측치 제어

#### 3.1  loc와 iloc를 활용한 행·열 선택

#### 3.2 불리언 인덱싱과 query() 조건 검색

불리언 인덱싱

query() 필터링

#### 3.3 결측치(Missing Data) 7대 처리 기법
3.3.1 결측치 탐지 및 현황 요약 (Detection)

3.3.2 결측치 삭제 (Drop)

3.3.3 통계적 대푯값 대치 (Imputation)

3.3.4 시계열 직전/직후 값 대치 (Forward / Backward Fill)

3.3.5 선형 보간법 (Linear Interpolation)

3.3.6 이상 기호 치환 및 수치형 변환 (Replace & Type Casting)

3.3.7 결측 여부 지표 변수 생성 (Missing Indicator)

#### 3.4 그룹화 집계(groupby)와 .to_numpy() 상호 변환